name: build-snapraid

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare release tag
      id: tag
      run: |
        # renovate: datasource=github-releases depName=amadvance/snapraid versioning=loose
        echo ::set-output name=SNAPRAID_VERSION::v11.4
    - name: Build snapraid
      run: |
        version=$(echo ${{ SNAPRAID_VERSION }} | cut -c 2-)
        sudo apt-get update
        sudo apt-get install -y gcc git make checkinstall curl libblkid1
        URL=https://github.com/amadvance/snapraid/releases/download/${{ steps.tag.outputs.SNAPRAID_VERSION }}/${version}.tar.gz
        echo $URL
        sudo curl -LO $URL
        sudo tar -xvf snapraid-${version}.tar.gz
        cd snapraid-$version
        sudo ./configure
        sudo make -j8
        sudo make -j8 check
        sudo checkinstall -Dy --install=no --nodoc
        sudo mkdir /build
        sudo cp *.deb /build/snapraid-${version}.deb
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.SNAPRAID_VERSION }}
        release_name: Release ${{ steps.tag.outputs.SNAPRAID_VERSION }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        version: $(echo ${{ SNAPRAID_VERSION }} | cut -c 2-)
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: /build/snapraid-${version}.deb
        asset_name: snapraid-${version}.deb
        asset_content_type: application/vnd.debian.binary-package
