name: build-snapraid

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build snapraid
      env:
        SNAPRAID_VERSION: 11.5
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc git make heckinstall curl libblkid1
        sudo curl -LO https://github.com/amadvance/snapraid/releases/download/v$SNAPRAID_VERSION/snapraid-$SNAPRAID_VERSION.tar.gz
        sudo tar -xvf snapraid-$SNAPRAID_VERSION.tar.gz
        sudo cd snapraid-$SNAPRAID_VERSION
        sudo ./configure
        sudo make -j8
        sudo make -j8 check
        sudo checkinstall -Dy --install=no --nodoc
        sudo mkdir /build
        sudo cp *.deb /build/snapraid-${SNAPRAID_VERSION}.deb
    - uses: actions/upload-artifact@v2
      env:
        SNAPRAID_VERSION: 11.5
      with:
        name: snapraid-${SNAPRAID_VERSION}.deb
        path: /build/snapraid-${SNAPRAID_VERSION}.deb
